### ISSUE TITLE
Mask's scalability

### ISSUE THREAD

**Issue by tassoman** [fballiano/p4a#28]
One of my Masks is now a big object defined by a file >600 lines because of UI and action methods.
Could you suggest any working example for slicing the big mask object in different chunks?
In my case there is a page with three tabs, I'd like to manage three different files, one for each tab.
I would declare click methods in a different file. To do so, should I use **namespaces** and **use**?

Another question is: how to load third parties, such as Zend Framework libraries, inside the mask object?

**Comment by fballiano** [comment]
Hi and sorry for the delay, i actually never had to split the mask, cause with phpstorm i manage also big php files without big troubles (folding, code structure and find works nice), i did some inheritance between masks but i don't think you can have a file for each tab.

you could use p4a's helpers to do some work on the mask or also php5.5's traits.

at the moment namespaces are not supported and i actually don't know what happens if you use namespaces in your app (never tried). for p4a 4.0 namespaces will be mandatory (something is already on github).

about loading 3rd party, you can simply put the into the libraries directory and use "require_once Zend/Pdf.php" (just a sample) everywhere you may need them. I also think there's some public code (some p4a plugin) which uses 3rd party libs.

let me know if you need anything more.
bye
fabrizio
